--------------------------------------------------------
--  文件已创建 - 星期一-六月-05-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMON
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_COMMON"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BLACKRECORD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BLACKRECORD" 
   (	"ID" NUMBER, 
	"SELFNAME" VARCHAR2(20 BYTE), 
	"BLACKNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COMPANY" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"LOCATION" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TRADE" VARCHAR2(20 BYTE), 
	"TIP" VARCHAR2(500 BYTE), 
	"SALARY" VARCHAR2(20 BYTE), 
	"PUBTIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE" 
   (	"ID" NUMBER, 
	"P_ID" NUMBER, 
	"C_ID" NUMBER, 
	"ISAGREED" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FRIENDRECORD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FRIENDRECORD" 
   (	"ID" NUMBER, 
	"SELFNAME" VARCHAR2(20 BYTE), 
	"FRIENDNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRADERECORD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GRADERECORD" 
   (	"ID" NUMBER, 
	"MINPOINT" NUMBER, 
	"MAXPOINT" NUMBER, 
	"GRADENAME" VARCHAR2(20 BYTE), 
	"ICONPATH" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBERINFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MEMBERINFO" 
   (	"ID" NUMBER, 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"AGE" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PROVINCECITY" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"PASSWORDQUESTION" VARCHAR2(200 BYTE), 
	"PASSWORDANSWER" VARCHAR2(200 BYTE), 
	"RECOMMENDER" VARCHAR2(20 BYTE), 
	"POINT" NUMBER DEFAULT 0, 
	"REGISTERDATE" DATE, 
	"LATESTDATE" DATE, 
	"STATUS" NUMBER DEFAULT 0, 
	"ISONLINE" NUMBER DEFAULT 0, 
	"GRADEID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBERSPACE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MEMBERSPACE" 
   (	"ID" NUMBER, 
	"OPINION" VARCHAR2(200 BYTE), 
	"RUNTIME" VARCHAR2(20 BYTE), 
	"RUNPLACE" VARCHAR2(20 BYTE), 
	"RUNSTAR" VARCHAR2(50 BYTE), 
	"RUNHABIT" VARCHAR2(50 BYTE), 
	"CELLPHONE" VARCHAR2(50 BYTE), 
	"ICON" VARCHAR2(200 BYTE), 
	"MEMBERID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MESSAGERECORD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MESSAGERECORD" 
   (	"ID" NUMBER, 
	"SENDER" VARCHAR2(20 BYTE), 
	"RECEIVER" VARCHAR2(20 BYTE), 
	"SENDDATE" DATE, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"SENDERSTATUS" NUMBER DEFAULT 0, 
	"RECEIVERSTATUS" NUMBER DEFAULT 0, 
	"STATUS" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PERSON" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(4 BYTE), 
	"BIRTHDAY" VARCHAR2(20 BYTE), 
	"SCHOOL" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TRADE" VARCHAR2(20 BYTE), 
	"SALARY" VARCHAR2(20 BYTE), 
	"TIP" VARCHAR2(200 BYTE), 
	"PUBTIME" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POINTACTION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POINTACTION" 
   (	"ID" NUMBER, 
	"ACTIONNAME" VARCHAR2(20 BYTE), 
	"POINT" NUMBER, 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POINTRECORD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."POINTRECORD" 
   (	"ID" NUMBER, 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"RECEIVEDATE" DATE, 
	"POINTACTIONID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BLACKRECORD
SET DEFINE OFF;
REM INSERTING into SYSTEM.COMPANY
SET DEFINE OFF;
Insert into SYSTEM.COMPANY (ID,USERNAME,PASSWORD,NAME,LOCATION,PHONE,EMAIL,TRADE,TIP,SALARY,PUBTIME) values (1,'sam2','jk123789','国信清软科技有限责任公司','山西太原','1212121','343242@qq.com','平面设计师','国信清软科技有限公司注册在北京中关村高科技园区，始创于2005年3月，已通过软件企业认证，是一家集实训、咨询、开发、服务于一体的高新技术产业公司。2008年被纳入“653工程”。国信清软科技有限公司2009年6月19日与中华人民共和国软件与集成电路促成中心达成战略合作伙伴关系。并承担中国JAVA软件工程师标准的制定，成为中国唯一的Java软件工程师标准制定企业。','3000-4000',to_date('04-3月 -17','DD-MON-RR'));
Insert into SYSTEM.COMPANY (ID,USERNAME,PASSWORD,NAME,LOCATION,PHONE,EMAIL,TRADE,TIP,SALARY,PUBTIME) values (138,'sam3','jk123789','华夏时代广告传媒有限公司','北京市海淀区','6093352','6093352@qq.com','网站策划','华夏时代·传媒成立于2005年，致力电视栏目制作、媒体代理发布、广告策划、创意制作、大型活动执行，是以媒体经营为依托、其它媒体服务并举的全方位媒体广告公司。

','6001-7000',to_date('05-6月 -17','DD-MON-RR'));
Insert into SYSTEM.COMPANY (ID,USERNAME,PASSWORD,NAME,LOCATION,PHONE,EMAIL,TRADE,TIP,SALARY,PUBTIME) values (2,'sam1','jk123789','企业金融服务山西中心','山西太原','8974562','2132131','平面设计师','人人行科技，依靠九鼎的雄厚实力和强大影响力，集结互联网、金融、支付、法律等领域的专业精英团队，着力为投资者打造个性化的融资及投资需求平台，开创创新型个人金融服务平台的先河。 ','7001-8000',to_date('19-4月 -17','DD-MON-RR'));
Insert into SYSTEM.COMPANY (ID,USERNAME,PASSWORD,NAME,LOCATION,PHONE,EMAIL,TRADE,TIP,SALARY,PUBTIME) values (139,'sam4','jk123789','瀚信企业管理咨询(上海)有限公司','上海市静安区北京西路968号嘉地中心808室','4049785','66666@qq.com','软件工程师','PKF，全称Pannell Kerr Forster，从1869年只有4间成员所（澳洲、加拿大、英国、美国）发展到如今在全球125个国家拥有超过440间成员所，21,400名拥有专业经验的合伙人和员工。2011年，PKF已跻身全球前10大知名会计师事务所之列，同时在咨询业也是名列前茅，当年PKF其全球营业额超过20亿美元。 ','4001-5000',to_date('05-6月 -17','DD-MON-RR'));
Insert into SYSTEM.COMPANY (ID,USERNAME,PASSWORD,NAME,LOCATION,PHONE,EMAIL,TRADE,TIP,SALARY,PUBTIME) values (140,'sam5','jk123789',' 南京壹进制信息技术股份有限公司 ','南京市秦淮区光华路1号（白下高新园区）斯坦德物联网大厦南楼8层','3723561','yijinzhi@163c.com','软件工程师','南京壹进制信息技术股份有限公司成立于2008年12月23日，注册资金2650万元，总部南京，在全国设立了20多个营销和服务分支机构。公司自成立以来秉承自主创新、自有品牌的经营理念，凝聚了众多高端技术人才，拥有多项发明专利和独立知识产权，是江苏省双软企业，产品通过多项国家认证。','5001-6000',to_date('17-4月 -17','DD-MON-RR'));
Insert into SYSTEM.COMPANY (ID,USERNAME,PASSWORD,NAME,LOCATION,PHONE,EMAIL,TRADE,TIP,SALARY,PUBTIME) values (141,'sam6','jk123789',' 广州水禾田软件科技有限公司 ','广州市白云区嘉禾望岗粤旺大厦B栋8307 ','4038521','4038521@qq.com','客户经理','广州水禾田软件科技有限公司成立于2010年，6年来我们一直以专业创造价值，用概念铸就品牌为目的。
公司团队日趋成熟，拥有资深的电子商务应用策划师，一流的网页设计师，经验丰富的程序员。
先后为政府、教育、医卫、部队、金融、交通、地铁、能源化工、房地产等行业用户以及外资、合资企业提供专业网站建设服务。','5001-6000',to_date('17-4月 -17','DD-MON-RR'));
REM INSERTING into SYSTEM.EMPLOYEE
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (39,27,1,0);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (110,41,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (111,32,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (40,27,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (44,32,1,0);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (112,99,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (122,121,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (124,123,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (126,125,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (162,161,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (164,163,2,1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (181,27,140,0);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (182,27,138,-1);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (183,27,141,0);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (184,27,139,0);
Insert into SYSTEM.EMPLOYEE (ID,P_ID,C_ID,ISAGREED) values (185,33,138,1);
REM INSERTING into SYSTEM.FRIENDRECORD
SET DEFINE OFF;
REM INSERTING into SYSTEM.GRADERECORD
SET DEFINE OFF;
Insert into SYSTEM.GRADERECORD (ID,MINPOINT,MAXPOINT,GRADENAME,ICONPATH) values (2,300,700,'璺戞灏忓皢','/images/face2.gif');
Insert into SYSTEM.GRADERECORD (ID,MINPOINT,MAXPOINT,GRADENAME,ICONPATH) values (3,700,1200,'璺戞鍋ュ皢','/images/face3.gif');
REM INSERTING into SYSTEM.MEMBERINFO
SET DEFINE OFF;
REM INSERTING into SYSTEM.MEMBERSPACE
SET DEFINE OFF;
REM INSERTING into SYSTEM.MESSAGERECORD
SET DEFINE OFF;
REM INSERTING into SYSTEM.PERSON
SET DEFINE OFF;
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (32,'zhangsan','123456','张三','男','1998-02-05','山西大学','13546869879','2432432423@qq.com','经济管理','4001-5000','积极向上',to_date('04-3月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (33,'lisi','123456','李四','男','1993-02-02','浙江大学','13502783214','21313123@abc.com','土木工程','6001-7000','刻苦努力',to_date('05-6月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (121,'lihongji','123456','李弘基','男','1998-03-31','西北农林大学','18703548975','4564545@qq.com','土木工程','7001-8000','勤奋好学,积极向上',to_date('15-4月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (27,'wangjiawei','123456','王嘉玮','女','1994-10-22','太原理工大学','18635162493','2411150704qq.com','数学','5001-6000','good person!',null);
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (41,'wangwu','123456','王五','男','1995-03-01','中北大学','18745120012','45454545@qq.com','法学','6001-7000','good',to_date('04-3月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (123,'renchang','123456','任畅','男','1994-02-14','太原理工大学','15476895200','323453@qq.com','数学','7001-8000','勤奋好学',to_date('16-4月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (125,'libai','123456','李白','男','1991-04-11','清华大学','13426835455','7866456@qq.com','软件工程','3000-4000','努力刻苦！！！',to_date('16-4月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (161,'lihao','123456','李昊','男','1994-04-07','武汉大学','18645310527','18645310527@qq.com','经济管理','7001-8000','自我评价良好！！',to_date('18-4月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (99,'daydream','jk123789','王威','男','1992-03-04','北京大学','15025470021','7654321@qq.com','软件工程','3000-4000',null,to_date('04-3月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (163,'wanglei','123456','王磊','男','1994-04-06','复旦大学','18635210517','18635210517@qq.com','软件工程','3000-4000','刻苦努力，勤奋好学',to_date('19-4月 -17','DD-MON-RR'));
Insert into SYSTEM.PERSON (ID,USERNAME,PASSWORD,NAME,SEX,BIRTHDAY,SCHOOL,PHONE,EMAIL,TRADE,SALARY,TIP,PUBTIME) values (55,'liuyu','123456','刘裕','男','1996-12-11','山西医科大学','13569360032','23432432@qq.com','软件工程','7001-8000',null,to_date('04-3月 -17','DD-MON-RR'));
REM INSERTING into SYSTEM.POINTACTION
SET DEFINE OFF;
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (1,'REGISTER',50,'娉ㄥ唽浼氬憳');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (2,'RECOMMEND',20,'鎺ㄨ崘浼氬憳');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (3,'LOGIN',3,'鐧诲綍');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (4,'LOGINDESKHELPER',3,'鐧诲綍妗岄潰鍔╂墜');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (5,'CREATEPERSONALSPACE',25,'鍒涘缓涓汉绌洪棿');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (6,'SENDSTICK',25,'鍙戝笘');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (7,'REPLYSTICK',25,'鍥炲笘');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (10,'BBSMANAGER',200,'鎴愪负鐗堜富');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (11,'REPLYSTICK',5,'姣?0涓洖澶嶅笘瀛愭ゼ涓?5');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (12,'EDM',10,'鎴愪负鐗堜富');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (14,'WINRUNNING1',5000,'閮藉競璺戞椿鍔ㄥ緱鍚嶆');
Insert into SYSTEM.POINTACTION (ID,ACTIONNAME,POINT,DESCRIPTION) values (15,'WINRUNNING2',4000,'閮藉競璺戞椿鍔ㄥ緱鍚嶆');
REM INSERTING into SYSTEM.POINTRECORD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYEE_PK" ON "SYSTEM"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004027
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004027" ON "SYSTEM"."GRADERECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004033
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004033" ON "SYSTEM"."MEMBERINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004037
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004037" ON "SYSTEM"."FRIENDRECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004040
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004040" ON "SYSTEM"."BLACKRECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004041
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004041" ON "SYSTEM"."MEMBERSPACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004044
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004044" ON "SYSTEM"."POINTACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004047
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004047" ON "SYSTEM"."POINTRECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004054
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004054" ON "SYSTEM"."MESSAGERECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004099
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004099" ON "SYSTEM"."COMPANY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C004100
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C004100" ON "SYSTEM"."PERSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BLACKRECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BLACKRECORD" MODIFY ("SELFNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."BLACKRECORD" MODIFY ("BLACKNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."BLACKRECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMPANY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FRIENDRECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FRIENDRECORD" MODIFY ("SELFNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FRIENDRECORD" MODIFY ("FRIENDNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FRIENDRECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRADERECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GRADERECORD" MODIFY ("MINPOINT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."GRADERECORD" MODIFY ("MAXPOINT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."GRADERECORD" MODIFY ("GRADENAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."GRADERECORD" MODIFY ("ICONPATH" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."GRADERECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBERINFO" MODIFY ("NICKNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MEMBERINFO" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MEMBERINFO" MODIFY ("GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MEMBERINFO" MODIFY ("AGE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MEMBERINFO" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MEMBERINFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERSPACE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBERSPACE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGERECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MESSAGERECORD" MODIFY ("SENDER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MESSAGERECORD" MODIFY ("RECEIVER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MESSAGERECORD" MODIFY ("SENDDATE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MESSAGERECORD" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MESSAGERECORD" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MESSAGERECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POINTACTION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POINTACTION" MODIFY ("POINT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."POINTACTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POINTRECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POINTRECORD" MODIFY ("NICKNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."POINTRECORD" MODIFY ("RECEIVEDATE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."POINTRECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "FK_C" FOREIGN KEY ("C_ID")
	  REFERENCES "SYSTEM"."COMPANY" ("ID") ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "FK_P" FOREIGN KEY ("P_ID")
	  REFERENCES "SYSTEM"."PERSON" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBERINFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBERINFO" ADD CONSTRAINT "INFO_GRADE" FOREIGN KEY ("GRADEID")
	  REFERENCES "SYSTEM"."GRADERECORD" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBERSPACE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBERSPACE" ADD CONSTRAINT "SPACE_INFO" FOREIGN KEY ("MEMBERID")
	  REFERENCES "SYSTEM"."MEMBERINFO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINTRECORD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."POINTRECORD" ADD CONSTRAINT "RECORD_ACTION" FOREIGN KEY ("POINTACTIONID")
	  REFERENCES "SYSTEM"."POINTACTION" ("ID") ENABLE;
